### ISSUE TITLE
GraphQL module example not working with graphql 15

### ISSUE THREAD

**Issue by tomasAlabes** [nestjs/graphql#742] opened 2020-04-03 19:22 UTC
## Bug Report

Sample: https://github.com/nestjs/nest/tree/master/sample/12-graphql-schema-first
The sample works with its graphql version `14.6.0`.

## Current behavior

```
$> nest start

/nest/sample/12-graphql-schema-first/node_modules/graphql/jsutils/devAssert.js:13
    throw new Error(message);
    ^

Error: Must provide Source. Received: undefined.
    at devAssert (/nest/sample/12-graphql-schema-first/node_modules/graphql/jsutils/devAssert.js:13:11)
    at new Parser (/nest/sample/12-graphql-schema-first/node_modules/graphql/language/parser.js:80:67)
    at Object.parse (/nest/sample/12-graphql-schema-first/node_modules/graphql/language/parser.js:35:16)
    at Object.<anonymous> (/nest/sample/12-graphql-schema-first/node_modules/@kamilkisiela/graphql-tools/dist/stitching/introspectSchema.js:39:42)
```

## Input Code

```shell
cd sample/12-graphql-schema-first
npm install --save graphql@15.0.0
npm start
```

## Expected behavior
Nest app running.

## Possible Solution
Adapt nest to the new graphql api.

## Environment
I found this creating today an app from scratch with the most basic graphql file. Then I went to the samples and found the difference.

nest version: 7.1.2
node version: v13.11.0
npm version: 6.13.7
yarn version: 1.22.4

**Comment by kamilmysliwiec** [comment] 2020-04-04 09:22
Fixed in `@nestjs/graphql@7.2.0`

**Closed by kamilmysliwiec** 2020-04-04 09:22 UTC

**Comment by Shahor** [comment] 2020-04-07 11:35
Mind sharing what the fix was?
REad through the code and didn't find for sure. 
I just upgraded as well and have this error.
This is the only recent issue I find talking about the problem

**Comment by kamilmysliwiec** [comment] 2020-04-07 17:41
@Shahor remove `node_modules`, `package-lock.json` and reinstall all packages. This issue is caused by the incompatibility between `graphql` latest version and other util graphql libs (like `merge-graphql-schema`)
