### ISSUE TITLE
Scope Request Global Guard not working on GraphQL

### ISSUE THREAD

**Issue by vinverdy** [nestjs/graphql#984] opened 2020-06-19 16:32 UTC
## Current behavior
hello resolvers ping function is not protected by guard

## Input Code
https://github.com/vinverdy/nest-graphql-issue-984

```ts
import { CanActivate, ExecutionContext, Injectable, Module, Scope } from '@nestjs/common';
import { APP_GUARD, NestFactory } from '@nestjs/core';
import { GraphQLModule, Query, Resolver } from '@nestjs/graphql';

@Resolver()
export class HelloResolvers {
  @Query(returns => Boolean)
  public ping(): boolean {
    return true;
  }
}

@Injectable({scope: Scope.REQUEST})
export class TestGuard implements CanActivate {
  public async canActivate(context: ExecutionContext): Promise<boolean> {
    return false;
  }
}

@Module({
  imports: [
    GraphQLModule.forRoot({
      autoSchemaFile: true,
    }),
  ],
  providers: [
    HelloResolvers,
    {
      provide: APP_GUARD,
      useClass: TestGuard,
    },
  ],
})
export class AppModule {}

(async () => {
  (await NestFactory.create(AppModule)).listen(3000);
})();
```

## Expected behavior
throw forbidden exception

## Environment

<pre><code>
Nest version: 7.1.3

 
For Tooling issues:
- Node version: 12  
- Platform:  Linux 

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment] 2020-06-22 06:16
Please provide a minimum reproduction repository.

**Comment by vinverdy** [comment] 2020-06-22 07:54
https://github.com/vinverdy/nest-graphql-issue-984

Please take a look, thanks in advance

**Comment by kamilmysliwiec** [comment] 2020-06-23 13:22
Duplicate of https://github.com/nestjs/graphql/issues/325

**Closed by kamilmysliwiec** 2020-06-23 13:22 UTC
Labels: needs clarification
