### ISSUE TITLE
schema.graphql generation broken after update

### ISSUE THREAD

**Issue by appinteractive** [nestjs/graphql#1726] opened 2021-08-27 16:24 UTC
## Bug Report
Currently the schema.graphql still uses multiline comments, which leads to an error in my tests.

## Current behavior
```GraphQLError: Syntax Error: Unexpected BlockString "What change was done?".```

## Input Code

```ts
registerEnumType(AuditAction, {
  name: 'AuditAction',
  description: 'What change was done?',
});
```

## Output schema.graphql
```graphql
"""What change was done?"""
enum AuditAction {
  APPROVED
  ASSIGNED
  ...
}
```

## Expected behavior
```graphql
# What change was done?
enum AuditAction {
  APPROVED
  ASSIGNED
  ...
}
```

## Possible Solution

Genrate correct comments with `#` instead of `"""`?
At least when I do a search and replace, it does work indeed. Which package is responsible for generating that?

## Environment
```json
{  
  "@nestjs/axios": "^0.0.1",
  "@nestjs/common": "8.0.6",
  "@nestjs/config": "1.0.1",
  "@nestjs/core": "8.0.6",
  "@nestjs/graphql": "^9.0.2",
  "@nestjs/platform-express": "^8.0.6",
  "apollo-server-express": "^3.3.0",
  "graphql": "^15.5.1",
  "graphql-tools": "8.1.0",
  "reflect-metadata": "0.1.13"
},
"devDependencies": {
  "@nestjs/cli": "8.1.1",
  "@nestjs/schematics": "^8.0.3",
  "@nestjs/testing": "8.0.6"
}
```
 
For Tooling issues:
- Node version: v14.17.3
- Platform: Mac

**Comment by elliotttf** [comment] 2021-08-30 11:58
FYI, I also experienced this error when upgrading from 9.0.0-next.7 to 9.0.2.

I don't have a minimal repo, but in my case I'm using a schema-first implementation. The offending schema looks like this:

```graphql
type Mutation {
  """
  Multiline comment that includes `inlineCodeFormat`

  As well as:
    - a list
    - of things
  """
  doMutation(mutationTypeType: String!): Boolean
}
```

**Comment by appinteractive** [comment] 2021-08-31 12:01
It seems to be resolved by calling the nest cli `nest update` but I`m not sure as I did upgrade the packages step by step again and so some versions hat minor bumps which could also have fixed them. 

@elliotttf can you try to run `nest update` too?

**Comment by appinteractive** [comment] 2021-08-31 12:16
Funny, on the build server the issue is back again.

**Comment by elliotttf** [comment] 2021-08-31 13:18
Unfortunately, the error persists for me after running `nest update`.

**Comment by Tony133** [comment] 2021-08-31 13:50
If you can leave minimal reproduction in a clonable git, the NestJS core team will investigate the issue.

**Comment by appinteractive** [comment] 2021-09-01 13:03
> If you can leave minimal reproduction in a clonable git, the NestJS core team will investigate the issue.

I know but I had to abort that as it took me more time then anticipated, for now I did downgrade to nest 7 with all packages pinned to the latest 7 version which works fine for now.

**Comment by anchan828** [comment] 2021-09-02 06:58
Hi, I had the same error.

This is minimal project.
https://stackblitz.com/edit/node-r7u1wy?file=index.ts

<img width="1092" alt="70d785b6329f6ef8717037127013894b" src="https://user-images.githubusercontent.com/694454/131797078-246b37e0-ee9d-48e6-a34f-0a2f569428bd.png">

**Comment by appinteractive** [comment] 2021-09-02 09:52
awesome @anchan828 🚀 with version 7 all works but with 8 it explodes 🧨 ... exactly that I see in my project.

**Comment by kamilmysliwiec** [comment] 2021-09-02 11:00
Can you test with 9.0.3? I reverted the `@graphql-tools/merge` package back to v6.2.5

**Comment by anchan828** [comment] 2021-09-02 12:38
@kamilmysliwiec Seems to be working fine!

https://stackblitz.com/edit/node-r7u1wy?file=index.ts

<img width="748" alt="240788e2cd7d2905b579d527030c0ad6" src="https://user-images.githubusercontent.com/694454/131844520-32500e8e-57cf-4e74-93c8-e2bb8aa7ff41.png">

**Comment by elliotttf** [comment] 2021-09-02 15:05
I can also confirm this is resolved with 9.0.3+. Thank you!

**Comment by appinteractive** [comment] 2021-09-02 20:23
6.2.5 is 10 months old, will that issue hit us again in the future? Needs something to be done here?

**Comment by anchan828** [comment] 2021-09-03 01:41
I think this issue is related. Just wait a little bit and it may be solved.
https://github.com/ardatan/graphql-tools/issues/3244

**Comment by kamilmysliwiec** [comment] 2021-09-03 06:40
Once it's fixed in the `@graphql-tools/merge`, I'll update to the latest version again.

**Comment by anchan828** [comment] 2021-09-04 04:20
Looks like it's fixed🥳
> handle descriptions and comments correctly during merge

https://github.com/ardatan/graphql-tools/releases/tag/%40graphql-tools%2Fmerge%408.1.1

**Closed** 2022-01-15 11:01 UTC
Labels: needs clarification
