### ISSUE TITLE
GraphQL: multiple endpoints not working [SOLUTION FOUND HERE!]

### ISSUE THREAD

**Issue by CYB3RL1F3** [nestjs/graphql#2453] opened 2022-10-16 10:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Hello,
Despite the search of different issues about this, the bug seems to still keep on existing.
I tried to create a couple of graphQL endpoints, to split admin and "public" resolvers.

In my app.module.ts

```
ProfileModule,
AdminProfileModule,
GraphQLModule.forRoot<ApolloDriverConfig>({
      driver: ApolloDriver,
      debug: config.isDev(),
      playground: true,
      autoSchemaFile: join(process.cwd(), 'src/schema.gql'),
      context: ({ req }) => ({ req }),
      transformAutoSchemaFile: true,
      include: [
        ProfileModule,
      ],
    }),
    GraphQLModule.forRoot<ApolloDriverConfig>({
      driver: ApolloDriver,
      debug: config.isDev(),
      playground: true,
      autoSchemaFile: join(process.cwd(), 'src/admin.gql'),
      context: ({ req }) => ({ req }),
      transformAutoSchemaFile: true,
      include: [
        AdminProfileModule,
      ],
    }),
```
While trying to debug I noticed that just the fact to add a GraphQLModule.forRoot, even with an empty includes array, even when not injecting AdminProfileModule, generated the following error : 

```
Schema must contain uniquely named types but contains multiple types named Links
```

ProfileModule and AdminProfileModule share some code, but two resolvers are different but with queries handling same name. For design reasons, I don't wanna change the names.

I think the bug is due to the fact that GraphQL.forRoot doesn't dive into "includes" modules, but check out for all imported modules. 

Could you check it out??

Thanks.

### Minimum reproduction code

https://gist.github.com/CYB3RL1F3/ad8962c3cb136a17d17410d29213cebc

### Expected behavior

Expected : 
Creating various graphql endpoints with a selection of modules handling resolvers.

### Package version

10.1.3

### Graphql version

`graphql`: 
`apollo-server-express`: 
`apollo-server-fastify`: 

### NestJS version

9.1.4

### Node.js version

16.3.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by smolinari** [comment] 2022-10-16 12:19
Duplicate of https://github.com/nestjs/graphql/issues/721

Scott

**Comment by CYB3RL1F3** [comment] 2022-10-16 13:35
Already seen, but this does not work actually. I don't wanna have 2 apps with workspaces because I simply can't manage two ports on the server. 
I did a little refactor to integrate GraphQL in a couple of modules separately but I can't have two instances of apps.

**Comment by CYB3RL1F3** [comment] 2022-10-16 14:33
This PR should be merged...
https://github.com/nestjs/graphql/pull/1432

**Comment by kamilmysliwiec** [comment] 2022-10-24 11:05
Duplicate https://github.com/nestjs/graphql/issues/721

**Closed by kamilmysliwiec** 2022-10-24 11:05 UTC
Labels: bug, needs triage
