### ISSUE TITLE
GraphQl Multiple Endpoints includes is ignored when using typeorm

### ISSUE THREAD

**Issue by kaufmo** [nestjs/graphql#896] opened 2020-05-25 06:38 UTC
## I'm submitting a...

<pre><code>
[x] Bug report
</code></pre>

## Current behavior

Hi, I want to use two endpoints in graphql (Code first). One for Admin and one for frontend. I also use typeorm for data management with postgres. When the typeorm module is loaded the graphql module ignores the include setting and uses all objects types that are defined and not the ones that are set in the include setting.

## Expected behavior

the two generated schemas(admin.gql / frontend.gql) only contains types that are included in the graphql module.

## Minimal reproduction of the problem with instructions

Code is protected, but if necessary i can create a step by step guide

## What is the motivation / use case for changing the behavior?

I want two apis that can be different with the role of the user. Some roles can see more data and some roles should see less.

## Environment

<pre><code>
Nest version: 7.0.9

 
For Tooling issues:
- Node version: 10.20.1  
- Platform:  Linux 

Others:

Operating system: Ubuntu 20.04
IDE: PHPStorm 2020.1.3
Package manager: npm 6.14.4
</code></pre>

**Comment by kamilmysliwiec** [comment] 2020-05-25 07:14
> Code is protected, but if necessary i can create a step by step guide

We can't help without having a minimum reproduction repository. Can you please share the instructions?

BTW I don't think that `TypeOrmModule` can affect the behavior of GraphQL, but I might be missing something. I suppose the issue is elsewhere.

**Comment by kaufmo** [comment] 2020-05-25 09:19
I've created an example now which should be nearly the same from my original code but only with two modules: https://github.com/kaufmo/nestjs-typeorm-multiple-graphql-bug 
There are two branches where you can check the settings. one with typeorm and one without.
I'm wondering now that i've become now on boths the same error. Eventually typeorm is not the problem you are right but what is wrong with that code?

**Comment by kamilmysliwiec** [comment] 2020-05-25 09:46
It's a duplicate of this issue then https://github.com/nestjs/graphql/issues/721. Let's track it there

**Closed by kamilmysliwiec** 2020-05-25 09:46 UTC
Labels: needs clarification
