### ISSUE TITLE
✨ FR: Support for Apollo Server 4

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [nestjs/graphql#2445] opened 2022-10-11 09:18 UTC
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

There is a RC for Apollo 4 and since the package structure for the express implementation changed I guess there need to be something done to enable support for apollo 4.

### Describe the solution you'd like

Make an Apollo Server version selection available so you can decide which implementation to use.

### What is the motivation / use case for changing the behavior?

New Apollo Server 4

**Comment by kamilmysliwiec** [comment] 2022-10-26 08:49
Would you like to create a PR for this issue?

**Comment by ThomasLohmann** [comment] 2022-11-24 11:43
Hi @sschneider-ihre-pvs @kamilmysliwiec any updates regarding this topic? 

It would be great to finalize it asap, since there are a couple of good improvements similar what GraphQL Yoga already provides: https://www.apollographql.com/blog/announcement/backend/apollo-server-4-a-lightweight-and-easier-to-use-apollo-server/ 

Best regards,
Thomas

**Comment by bedcoding** [comment] 2022-11-27 09:23
If support for v3 graphql is dropped, will I not be able to npm install nestJS?

**Comment by bedcoding** [comment] 2022-11-27 09:26
1) If v3 apollo server support is discontinued, will nestJS using v3 apollo server break?
2) If apollo-server-express package is deleted, will I still be able to install it through yarn?

**Comment by bedcoding** [comment] 2022-11-28 00:46
1. I saw the phrase that apollo server v3 is shutting down.
If Apollo Server v3 is deprecated, will all the libraries and frameworks that use it be unavailable for 'npm install'?
https://www.apollographql.com/docs/apollo-server/v3
![스크린샷 2022-11-28 오전 9 08 30](https://user-images.githubusercontent.com/33927558/204167299-883e5068-54ba-46b5-bcc9-76245d9b4725.jpg)


2. By the way, nestJS, which I am currently using, was also using v3 internally.
https://github.com/nestjs/nest/blob/master/package.json
![스크린샷 2022-11-28 오전 9 15 37](https://user-images.githubusercontent.com/33927558/204167718-19b8d231-0d6f-4e41-9d85-385307a08bed.jpg)


3. The official document of nestJS also instructs me to npm install the apollo-server-express that exists in the v3 version.
What should I do? I'm so afraid I don't know what I can do to prevent a disaster.
https://docs.nestjs.com/graphql/quick-start
![스크린샷 2022-11-28 오전 9 09 21](https://user-images.githubusercontent.com/33927558/204167861-e62233df-72c4-43ae-87aa-f3e2fad02a99.jpg)

**Comment by kamilmysliwiec** [comment] 2022-11-28 07:38
You can safely keep using v3 for now. It won't be removed, it's just deprecated. We'll eventually migrate `@nestjs/apollo` to use v4 too

**Comment by sschneider-ihre-pvs** [comment] 2022-11-28 09:07
> Would you like to create a PR for this issue?

I guess I lack the knowledge to be able to do that.

**Comment by sschneider-ihre-pvs** [comment] 2022-11-28 10:47
I just had a look and the migration is not that trivial in my opinion since it drops a lot of stuff that is currently used, like the ApolloErrors, and not every error code made it to the replacement enum. Also the applyMiddleware is dropped so the usual app.use is not used and cors and so on have to be applied manually, I couldn't find the express initialization anywhere so I am not sure where to apply the middleware. The list goes on :D

**Comment by Maxwell2022** [comment] 2022-12-07 20:49
Yes, it's a tricky one... I myself don't have the full knowledge of how this is working under the hood, but here are few things to consider:

- This package needs to be server agnositic, meaning we should be able to use it with Express or Fastify. I wonder if we should inject the server instance in the configuration for this package, so that devs have full control of their other middlewares inside the nest application (ie. cors)
- @apollo/server is including their middleware for express and fastify. Ideally we'd want to check the instance of the server that is injected and apply the correct middleware?
- I'm wondering if we need to maintain all these Apollo error in this package, I think the fact that Apollo v4 drop them, we should do the same and just rely on whatever Apollo is returning (we don't want some strange error wrapping)

**Comment by luas10c** [comment] 2022-12-19 05:33
I intend to deliver the upgrade to v4

**Comment by sam-super** [comment] 2022-12-22 10:40
@luas10c but are you thinking about replacing `apollo-server-fastify` with: https://www.npmjs.com/package/@as-integrations/fastify as part of the upgrade work?

I would also be keen to help with this if you are interested (i don't have much experience of the codebase though).

**Comment by sschneider-ihre-pvs** [comment] 2022-12-22 10:52
> I intend to deliver the upgrade to v4

that is good news

**Comment by luas10c** [comment] 2022-12-23 02:51
> @luas10c are you thinking about replacing `apollo-server-fastify` with: https://www.npmjs.com/package/@as-integrations/fastify as part of the upgrade work?
> 
> I would also be keen to help with this if you are interested (i don't have much experience of the codebase though).

Well apollo/server v4 doesn't support fastify layer yet, I'm thinking of upgrading to express layer only

**Comment by luas10c** [comment] 2022-12-23 08:25
https://github.com/luas10c/graphql/tree/upgrade-apollo-v4

I'm pushing updates to this branch

**Comment by timonmasberg** [comment] 2022-12-23 09:58
> https://www.npmjs.com/package/@as-integrations/fastify

Very nice! Can I help in any way? When do you intend to open a PR for this?

**Comment by luas10c** [comment] 2022-12-23 09:59
![image](https://user-images.githubusercontent.com/66514698/209314990-476846ac-fe32-4567-9271-0085f7b8a372.png)

Update for @apollo/server v4 is partially ready, I hope you can see the branch and fix possible bugs and test errors.

**Comment by luas10c** [comment] 2022-12-23 10:00
> Very nice! Can I help in any way? When do you intend to open a PR for this?

you can, you can open a pull request that we will accept.

**Comment by luas10c** [comment] 2022-12-23 10:02
Added a new feature that comes from @nestjs/graphql named GraphQLException to throw exceptions to the apollo graphql server

With this, the server can now identify several success messages 200, redirection messages 300, client errors 400 and server errors 500

**Comment by rohanrajpal** [comment] 2023-01-03 06:37
> > Very nice! Can I help in any way? When do you intend to open a PR for this?
> 
> you can, you can open a pull request that we will accept.

Thanks for efforts on supporting Apollo V4! I guess @timonmasberg meant when do you intend to make a PR to this repository so that your changes can eventually be merged to main.

**Comment by luas10c** [comment] 2023-01-15 09:04
Much of it is implemented needs to fix tests, if anyone can contribute to this update it will all be welcome.

https://github.com/luas10c/graphql/tree/upgrade/apollo-v4

**Comment by lpessoa** [comment] 2023-01-29 01:31
@luas10c I've had a look at your fork and it looks great! 

I had some issues running it like so 
``` typescript
 const app = await NestFactory.create<NestFastifyApplication>(AppModule, new FastifyAdapter());
 app.listen(3000);
```
 I would hit 
``` sh
AvvioError: Plugin did not start in time: 'middlewareWrapper'. You may have forgotten to call 'done' function or to resolve a Promise
```
due to 
``` typescript
await app.register(cors, options.cors);
```
by removing it the server starts up nicely and the GraphQL endpoint works like a charm

Can I join you on this one?

**Comment by luas10c** [comment] 2023-01-29 09:57
> @luas10c I've had a look at your fork and it looks great!
> 
> I had some issues running it like so:
> 
> ```ts
>  const app = await NestFactory.create<NestFastifyApplication>(AppModule, new FastifyAdapter());
>  app.listen(3000);
> ```
> 
> The server would not start and after some time (related to fastify plugin timeout configuration) I would get the following error:
> 
> ```shell
> AvvioError: Plugin did not start in time: 'middlewareWrapper'. You may have forgotten to call 'done' function or to resolve a Promise
> ```
> 
> After some digging I found out the problem resides on the following code:
> 
> ```ts
> await app.register(cors, options.cors);
> ```
> 
> by removing it the server starts up nicely and the GraphQL endpoint works like a charm. Maybe we should replace this code to use the **@fastify/cors** package instead.
> 
> Can I join you on this one?

All right, correct that part and mention you as co-author of the commit. thank you very much will contribute a lot to the community.

**Comment by luas10c** [comment] 2023-01-29 09:59
@lpessoa 

If you find more inconveniences let us know, if you have a suggestion on how to get to the solution it will be welcome.

**Comment by luas10c** [comment] 2023-01-29 10:01
I used dynamic imports, since it's like peerDependencies.

If you are using the expression layer you also install the cors dependencies. now if you chose to use fastify you will have to install @fastify/cors in your project.

**Comment by luas10c** [comment] 2023-01-29 10:02
We can create a discussion of what would be better to have these dependencies managed by packages or not.

**Comment by lpessoa** [comment] 2023-01-31 01:53
@luas10c I've started updating the tests to the new APIs. I'll work on my fork from your repo and then create a PR. 
Does it sound good to you @kamilmysliwiec ?

**Comment by luas10c** [comment] 2023-01-31 02:25
It would be nice to complete the tests, and we deliver a Pull Request all together.

**Comment by lpessoa** [comment] 2023-01-31 03:09
> It would be nice to complete the tests, and we deliver a Pull Request all together.

Yes! I'll open my PR pointing to your fork 😃

**Comment by sschneider-ihre-pvs** [comment] 2023-01-31 08:43
@kamilmysliwiec can you close https://github.com/nestjs/graphql/pull/2525 that seems outdated and was a draft only anyway

**Comment by paologf** [comment] 2023-02-01 16:44
@luas10c thanks for your effort! 🍻

I'm trying the package in my project, firs of all I had to remove some git conflicts markers in package.json ( see [pull request](https://github.com/luas10c/graphql/pull/1) ) that gives errors during installation, but I still have an issue that I don't understand..

I install and build the package in a container with node18, then I use `yarn link` to link to my project. 
This are the dependencies in package.json:

```
  "dependencies": {
    "@nestjs/common": "^9.2.1",
    "@nestjs/config": "^2.2.0",
    "@nestjs/core": "^9.2.1",
    "@nestjs/platform-express": "^9.2.1",
    "@types/node": "^18.11.18",
    "class-transformer": "^0.5.1",
    "class-validator": "^0.14.0",
    "graphql": "^16.6.0",
    "reflect-metadata": "^0.1.13",
    "ts-node": "^10.9.1"
  },
  "devDependencies": {
    "@nestjs/cli": "^9.0.0",
    "@nestjs/schematics": "^9.0.0",
    "@nestjs/testing": "^9.0.0"
  },

```

My main and app.module files are as following:

```
// main.ts
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  await app.listen(3000);
}
bootstrap();

// app.module.ts
import { Module } from '@nestjs/common';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { ConfigModule } from '@nestjs/config';
import { GraphQLModule } from '@nestjs/graphql-workspace/packages/graphql';
import { ApolloDriver, ApolloDriverConfig } from '@nestjs/graphql-workspace/packages/apollo';

@Module({
  imports: [
   GraphQLModule.forRootAsync<ApolloDriverConfig>({
      driver: ApolloDriver,
	imports: [ConfigModule],
	inject: [ConfigService],
        useFactory: async (configService: ConfigService) => ({
	  debug: configService.get<boolean>('GQL_DEBUG', false),
	  playground: configService.get<boolean>('GQL_PLAYGROUND', false),
	  tracing: configService.get<boolean>('GQL_TRACING', false),
	  context: ({ req }) => ({ req }),
	  typePaths: ['./**/*.gql'],
	})
    }),
    ConfigModule,
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}

```

, I got this error:

```
[Nest] 55  - 02/01/2023, 4:22:09 PM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the GraphQLModule (?, GqlModuleOptions, AbstractGraphQLDriver, GraphQLTypesLoader). Please make sure that the argument HttpAdapterHost at index [0] is available in the GraphQLModule context.

Potential solutions:
- Is GraphQLModule a valid NestJS module?
- If HttpAdapterHost is a provider, is it part of the current GraphQLModule?
- If HttpAdapterHost is exported from a separate @Module, is that module imported within GraphQLModule?
  @Module({
    imports: [ /* the Module containing HttpAdapterHost */ ]
  })
```

If I restore `@nestjs/graphql` and `@nestjs/apollo` ( installing `apollo-server-core` and `apollo-server-express`  ) it goes fine.

I don't know if the issue is in building/importing your package or something else.. do you have any idea?
Thanks

**Comment by luas10c** [comment] 2023-02-01 17:37
@paulogf

As you are using a workspace, you can delete the node_modules folder created in your application and install, who manages the dependencies is a global node_modules.

**Comment by abulhuman** [comment] 2023-02-01 20:41
I was checking out Apollo v4 for a new app since the v3 is not going to last that long and spending any effort on a project with it would be futile piling up unnecessary technical debt since I would be forced to switch to v4 soon. So, I was wondering how far on the roadmap to Apollo v4 + NestJS GraphQL we are. 
FYI: I enjoyed reading this entire thread seeing the magic of open source firsthand. I am aware of the progress made by @luas10c , @lpessoa and everybody else involved in here. I only want to know how optimistic I should sound in expecting the v4 upgrade when I pitch it to my boss on the next stand-up.

**Comment by luas10c** [comment] 2023-02-01 21:07
We look forward to delivering apollo v4 as soon as possible.

**Comment by andrewmclagan** [comment] 2023-02-02 05:38
Thanks for all your hard work @luas10c and everyone else involved. Very appreciated!

**Comment by paologf** [comment] 2023-02-02 15:56
> @paologf
> 
> As you are using a workspace, you can delete the node_modules folder created in your application and install, who manages the dependencies is a global node_modules.
> 
> Deleting the node_modules folder that should be created in your project will resolve the issue.

Thanks, this seems working ( @lpessoa no need of verdaccio, but it's something to keep in mind 😊 ).

I'll wait till implementations is ended to check something that currently gives me error ( for example emtpy GqlExecutionContext in custom decorators). 😉

**Comment by eonae** [comment] 2023-02-06 12:05
Thank you all of your work. Much appreciate it. And looking forward to use apollo4 with Nest

**Comment by lpessoa** [comment] 2023-02-06 12:13
Hi all.. me and @luas10c are almost finished with the tests and will be creating a PR very shortly. 

We do have some tiny questions though:
- since we do have to upgrade mercurius to work with the new fastify version which version should we set as the minimum required?
- There are some TODOs related to some doubts regarding error handling. Apollo V4 drastically changes error handling and does not propagate the http response error in extensions anymore. Maybe we should look into also proposing a change to Apollo.

What do you guys think ?

**Comment by timonmasberg** [comment] 2023-02-06 12:25
> 

In https://www.apollographql.com/docs/apollo-server/integrations/building-integrations#handle-errors they state that you do not need any special handling for errors with the express integration. IDK how we should handle fastify.

**Comment by lpessoa** [comment] 2023-02-06 12:43
@timonmasberg we were able to pinpoint to https://github.com/apollographql/apollo-server/blob/28629243c495b6e6caa0da4eaacc8b10c727f2ac/packages/server/src/errorNormalize.ts#L58 , the error thrown does not have any details inside the extension object. Apollo server then just fills it out with an internal server error and no further details.

**Comment by timonmasberg** [comment] 2023-02-06 12:46
> @timonmasberg we were able to pinpoint to https://github.com/apollographql/apollo-server/blob/28629243c495b6e6caa0da4eaacc8b10c727f2ac/packages/server/src/errorNormalize.ts#L58 , the error thrown does not have any details inside the extension object. Apollo server then just fills it out with an internal server error and no further details.

Ah I get it, ye, in the [changelogs](https://www.apollographql.com/docs/apollo-server/migration/#apolloerror) they stated that you have to fill out the extension details on your own. What details do we exactly need there? Isn't the plain GraphqlError enough?

**Comment by lpessoa** [comment] 2023-02-06 14:58
> > @timonmasberg we were able to pinpoint to https://github.com/apollographql/apollo-server/blob/28629243c495b6e6caa0da4eaacc8b10c727f2ac/packages/server/src/errorNormalize.ts#L58 , the error thrown does not have any details inside the extension object. Apollo server then just fills it out with an internal server error and no further details.
> 
> Ah I get it, ye, in the [changelogs](https://www.apollographql.com/docs/apollo-server/migration/#apolloerror) they stated that you have to fill out the extension details on your own. What details do we exactly need there? Isn't the plain GraphqlError enough?

It should be enough but we do have some test scenarios in the lib that are expecting additional info i.e

``` javascript
.expect(200, {
        data: null,
        errors: [
          {
            extensions: {
              code: 'BAD_USER_INPUT',
              response: {
                error: 'Bad Request',
                message: [
                  'description must be longer than or equal to 30 characters',
                ],
                statusCode: 400,
              },
            },
            message: 'Bad Request Exception',
          },
        ],
      });
```

was changed to

``` javascript
.expect(200, {
        data: null,
        errors: [
          {
            message: 'Bad Request Exception',
            locations: [{ line: 2, column: 3 }],
            path: ['addRecipe'],
            // TODO: validate behaviour from apollo v4
            extensions: { code: 'INTERNAL_SERVER_ERROR' },
          },
        ],
      });
```

**Comment by kamilmysliwiec** [comment] 2023-02-06 15:19
@luas10c could you create a PR with the current progress? I can double-check everything and fil the gaps

**Comment by luas10c** [comment] 2023-02-06 16:57
We're updating in a separate repository so we can send a PR later with everything ready.

https://github.com/luas10c/graphql

**Comment by timonmasberg** [comment] 2023-02-06 17:26
> @kamilmysliwiec
> 
> We're updating in a separate repository so we can send a PR later with everything ready.
> 
> https://github.com/luas10c/graphql

Just open a draft PR, it is more convenient and there the maintainers can already start reviewing and comment on it.

**Comment by kamilmysliwiec** [comment] 2023-02-07 08:04
Let's track this here https://github.com/nestjs/graphql/pull/2631

**Closed by kamilmysliwiec** 2023-02-07 08:04 UTC
Labels: feature

**Comment by coler-j** [comment] 2023-02-10 00:25
Is there an issue to track updating the docs to support v4?

**Comment by kamilmysliwiec** [comment] 2023-02-10 07:42
Docs won't need many changes (it boils down to swapping dependencies that should be installed/imported in samples - compared to the previous version).
