### ISSUE TITLE
Null value in response

### ISSUE THREAD

**Issue by hxdef2517** [nestjs/graphql#96] opened 2018-12-21 08:09 UTC
I have a graphql query which return a result of closest distances to destination objects.

**Schema:**

```
type Query {
  getDestinationsByDistance(location: InputCoordinates, radius: Int): DestinationsResponse
}

type DestinationsResponse {
    success: Boolean!
    destinations: [Destination]
    errors: [Error!]
}

type Error {
    path: String!
    message: String
}

input InputCoordinates {
  lat: Float
  lng: Float
}

type Destination {
  id: Int
  application: Application!
  name: String
  location: Geometry
  arrived_at: Date
  createdAt: Date
  updatedAt: Date
  deletedAt: Date
  distance: Float <- extra field which doesn't exists on entity and db table
}
```

**Resolver:**

```
@Query('getDestinationsByDistance')
  @UseGuards(DestinationsGuard)
  async getDestinationsByDistance(@Args('location') location: InputCoordinates, @Args('radius') radius: number) {
    return await this.destinationsService.findDestinationsWithingRadius(location, radius);
  }
```

**findDestinationsWithingRadius Service Response sample :**

```
{
    "success": true,
    "destinations": [
        {
            "id": 5,
            "application_id": 4,
            "name": "Place A",
            "location": {
                "type": "Point",
                "coordinates": [
                    1.00000,
                    2.00000
                ]
            },
            "arrivedAt": null,
            "createdAt": "2018-10-05T08:48:07.000Z",
            "updatedAt": "2018-10-05T08:48:07.000Z",
            "deletedAt": null,
            "distance": 180.2908047894669
        },
...
```

**Entity:**

```
const tableOptions: IDefineOptions = {
    timestamp: true,
    tableName: 'destinations'
} as IDefineOptions;

@Table(tableOptions)
export class Destinations extends Model<Destinations> {

    @Column({
        type: DataType.INTEGER(11),
        allowNull: false,
        autoIncrement: true,
        unique: true,
        primaryKey: true
    })
    public id: number;

    @ForeignKey(() => Applications)
    @Column({
        type: DataType.INTEGER(11),
        allowNull: false,
    })
    public application_id: number;

    @Column({
        type: DataType.STRING(255),
        allowNull: false
    })
    public name: string;

    @Column({
        type: DataType.GEOMETRY,
        allowNull: false
    })
    public location: object;

    @Column({ type: DataType.DATE,
        field: 'arrived_at' })
    public arrivedAt: Date;

    @CreatedAt public createdAt: Date;

    @UpdatedAt public updatedAt: Date;

    @DeletedAt public deletedAt: Date;

    @BelongsTo(() => Applications, {
        as: 'application',
        foreignKey: 'application_id',
        onDelete: 'no action'
    })
    public application: Applications;
}
```

So my **Destinations Entity** doesn't have distance field, but GraphQL query response return distances to the destinations objects counted by ST_Distance_Sphere and have a distance attribute. When I run GraphQL query, the response its correct but distance field is empty since its doesn't exists in entity and database table, so I manually added to GraphQL schema but response value is null for all Distances. How can I fix this and show distance counted by query in GraphQL response ?

**GraphQL Response sample:**

```
{
  "data": {
    "getDestinationsByDistance": {
      "destinations": [
        {
          "id": 5,
          "name": "Point A",
          "distance": null
        },
        {
          "id": 10,
          "name": "Point B",
          "distance": null
        },
```

**Query:**

```
query getDestinationsByDistance($location: InputCoordinates!, $radius: Int!) {
  getDestinationsByDistance(location: $location, radius: $radius) {
    destinations {
      id
      name
      distance
    }
  }
}
```

**Comment by hxdef2517** [comment] 2018-12-21 08:42
Update: After adding field to db and defining it inside Destinations Entity response filling up results correctly. Is there a way to use some "virtual" fields and not define a real ones ?

**Comment by Aidurber** [comment] 2018-12-23 11:05
Is your service method `findDestinationsWithingRadius` returning `distance`? If you're returning a raw entitity, you might want to consider using DTOs/Models. 


```typescript
export class DestinationDto {
  constructor(destination?: Destination, distance?: number) {
    if (destination) {
      this.id = destination.id;
      this.name = destination.name;
      this.distance = distance;
    }
  }

  id: number;
  name: string;
  distance: number;
}

```

And in your service something like:

```typescript
  async findDestinationsWithingRadius(location: string, radius: number) {
    // Retrieve the destinations within the radius, your current service logic
    const destinations = this.destinationRepository.find({
      /** */
    });
    const models = destinations.map(destination => {
      // Not sure where you calculate distance
      const distance = calcDistance(destination);
      return new DestinationDto(destination, distance);
    });
    return models;
  }

```

Nest GraphQL will just take the values from the returned object.

**Comment by Aidurber** [comment] 2018-12-25 16:59
@hxdef2517 Yeah as long as the data is in the model, the resolver can access it. I was unsure on your whole  data structure. Glad it worked out for you. If the issue is resolved, could you close this issue? Helps the maintainers.

**Closed** 2018-12-29 12:35 UTC

**Comment by scopsy** [comment] 2020-02-19 15:05
If none of the above helped, and you have a global interceptor that envelopes all the responses for example inside a "data" field, you must disable it for graphql other wise graphql resolvers convert to null.
